apiVersion : apps/v1
kind: Deployment
metadata:
  name: "journalappaks-9725"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "journalappaks-9725"
  template:
    metadata:
      labels:
        app: "journalappaks-9725"
    spec:
      containers:
        - name: "journalappaks-9725"
          image: "journalappaks.azurecr.io/journalappaks"
          ports:
          - containerPort: 80